### ISSUE TITLE
Try to use strings for 'types' instead of integers

### ISSUE THREAD

**Issue by marcofucci** [UKTradeInvestment/export-wins-data#7]
Using strings for 'type' fields instead of integers (e.g. https://github.com/UKTradeInvestment/export-wins-data/blob/master/wins/models.py#L27) makes it easier to look at the database without having the matching labels with you.

**Comment by danielquinn** [comment]
I don't know about this one.  I generally don't like using arbitrary strings unless they reflect some sort of standard if for no other reason than integers take up much less space than repeated strings.

So for example, a list of countries should be stored with ISO country codes, but a list of types of peanut butter, should be stored as integers since there's no official meaning associated.  Do you see this as more of a style thing or are you adamant about this one?

**Comment by marcofucci** [comment]
yeah it's a style thing. What you said applies to integers as well, there's really no official meaning associated to integers. Between arbitrary numbers and somewhat meaningful strings, I usually prefer the latter but we don't have to agree.
I'll close this one.
